### ISSUE TITLE
http, cors 과제 제출 

### ISSUE THREAD

**Issue by sae2say** [likelion-Inha-12/sae2say#11]
작성한 노션 화면 캡쳐하여 과제 제출합니다! 

![image](https://github.com/likelion-Inha-12/sae2say/assets/132613722/461596f3-a6b7-4847-9202-463a50f49ddb)

![image](https://github.com/likelion-Inha-12/sae2say/assets/132613722/3a55b505-86da-471d-816a-d6c70c2e5226)

![image](https://github.com/likelion-Inha-12/sae2say/assets/132613722/6174d5b1-ba99-48f0-9cb1-e1ddc915ee0d)

![image](https://github.com/likelion-Inha-12/sae2say/assets/132613722/6a5a0613-84a4-4975-b66b-a0ea8192ba74)

**Comment by juwon0403** [comment]
1) URL 구조 부분에서 도메인 뒤에 **:포트** 추가
2) 같은 출처? 다른 출처? 표에 포트 번호는 언급되지 않았지만, 출처 확인할 때  포트번호까지 반드시 확인해줘야 한다는 거! 포트가 명시되어 있지 않다면 프로토콜의 기본 포트 번호(http의 기본 포트는 80, https의 기본 포트는 443)를 사용한다는 것도 알고 있으면 좋을 거 가타

나머지 부분은 아주 훌륭행
수고많아써 세희~~
