### ISSUE TITLE
배포 과제 제출합니다. 

### ISSUE THREAD

**Issue by sae2say** [likelion-Inha-12/sae2say#9]
![image](https://github.com/likelion-Inha-12/sae2say/assets/132613722/b4f82cf9-2ea9-4407-b197-a2742abc03c8)

![image](https://github.com/likelion-Inha-12/sae2say/assets/132613722/7c383f5f-047a-4376-9d8f-48c9177ef831)

탄력적IP/health/이나 탄력적IP/admin/ 처럼 제 프로젝트에 등록된 url을 쳤을 땐 문제가 없는데, 
탄력적IP 만 쳤을 때 세션 자료처럼 로켓 그림 있는 페이지가 안뜨고 404가 뜹니다. ㅠㅠ .. 왜 그런 걸까요? ㅠㅠ.

**Comment by juwon0403** [comment]
결론적으로는 404가 뜨는 게 마자용

내가 배포한 사이트에 로켓 모양이 떴던 이유는 지정한 url이 하나도 없었기 때문이더라구,,
너가 만든 플젝에는 "지정된 url이 존재 + 기본 경로는 지정X"라서 404 뜨는 게 마자!
그래서 지정된 url인 /health/에 접속하면 프로젝트 내에 만들어져 있던 페이지인 'seminar server ok'가 뜨는 거야

참 잘했서요 수고했어~~

**Comment by sae2say** [comment]
엉!!!! 감사합니다 ~~!!!
